# Generated by Django 2.1.7 on 2019-03-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.List'),
        ),
    ]
