# Generated by Django 2.1.7 on 2019-03-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.CharField(default='anonymous', max_length=255),
        ),
    ]
