# Generated by Django 2.1.7 on 2019-03-18 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190318_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('checked', models.BooleanField(default=False)),
                ('header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.List')),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='header',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
