# Generated by Django 2.1.7 on 2019-03-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_entry_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='collapsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
